Announce 0.3
Francis Galiegue (25):
      Redirect to the wiki for processor descriptions
      Start and write the Avro to JSON Schema converter processor
      Implement Avro simple type conversions
      pom.xml: exclude jersey-core from jjschema
      Avro2JsonSchemaProcessor: change strategy
      Avro processor: a lot of changes
      Avro: more work
      Avro: implement "fixed" type conversion
      Avro: add enum translation
      Avro: add array translation
      Avro: add union handling
      Avro: do "record" translation
      pom.xml: update avro dependency
      More updates to Avro
      Add tests with original test files from the Apache Avro svn
      Avro: reorganize fields in records, add doc in enum
      Avro: more minor cleanups, and fix a test
      Avro2JsonSchemaProcessorTest: check that the generated schemas are valid
      Avro: more cleanups
      Remove test files
      Avro: exclude more unneeded dependencies
      Avro: some more changes
      Test thread safety of Avro processor as well
      Avro: fix problems with NoSuchMethodError
      0.3

Signed-off-by: Francis Galiegue <fgaliegue@gmail.com>